# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 00:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('drink', models.BooleanField()),
                ('date', models.DateTimeField()),
                ('password_reg', models.CharField(max_length=50)),
                ('password_acc', models.CharField(max_length=50)),
                ('contact', models.TextField()),
                ('description', models.TextField()),
                ('stripe_user_id', models.CharField(default='SOME STRING', max_length=140)),
                ('address', models.CharField(max_length=50)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
