# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 20:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='event',
            name='date',
        ),
        migrations.RemoveField(
            model_name='event',
            name='drink',
        ),
        migrations.RemoveField(
            model_name='event',
            name='password_acc',
        ),
        migrations.RemoveField(
            model_name='event',
            name='price',
        ),
    ]
