# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 17:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20170219_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='type',
            field=models.CharField(choices=[('DM', 'Demande'), ('RE', 'Reponse')], default='DM', max_length=2),
        ),
    ]
