# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20170219_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
