# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 15:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_list_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='password_reg',
        ),
        migrations.AddField(
            model_name='event',
            name='date',
            field=models.DateField(default=datetime.date(2017, 2, 20)),
        ),
        migrations.AddField(
            model_name='event',
            name='drink',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='food',
            field=models.BooleanField(default=False),
        ),
    ]
