# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 15:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_auto_20170220_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
