# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 00:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic_url', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('numero', models.CharField(blank=True, max_length=10)),
                ('age', models.CharField(blank=True, max_length=50)),
                ('profession', models.CharField(blank=True, max_length=50)),
                ('provider', models.BooleanField(default=False)),
                ('access_token', models.CharField(max_length=50)),
                ('stripe_user_id', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
