# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 18:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accueil', '0002_auto_20170216_1336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='access_token',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='stripe_user_id',
        ),
    ]
